AllCops:
  DisplayCopNames: true
  Exclude:
    - bin/*
    - db/schema.rb
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
